-- Refresh free-weight demos (3 per muscle filter) + replace broken machine videos.

insert into public.gym_exercises (
  slug, name, muscle_group, equipment, difficulty, duration_seconds,
  demo_video_url, demo_thumbnail_url, cues
) values
  -- Legs (3)
  ('bodyweight-squat', 'Bodyweight squat', 'legs', 'bodyweight', 'beginner', 45,
   'https://www.youtube.com/embed/aclHkVaku9U', 'https://img.youtube.com/vi/aclHkVaku9U/hqdefault.jpg',
   'Feet shoulder-width, sit back, knees track over toes.'),
  ('walking-lunge', 'Walking lunge', 'legs', 'bodyweight', 'intermediate', 50,
   'https://www.youtube.com/embed/L8fvypPrzzs', 'https://img.youtube.com/vi/L8fvypPrzzs/hqdefault.jpg',
   'Long stride, front knee stacked above ankle.'),
  ('goblet-squat', 'Goblet squat', 'legs', 'dumbbell', 'beginner', 45,
   'https://www.youtube.com/embed/MeIiIdhvXT4', 'https://img.youtube.com/vi/MeIiIdhvXT4/hqdefault.jpg',
   'Hold the weight at your chest, sit deep, keep elbows inside the knees.'),

  -- Chest (3)
  ('push-up', 'Push-up', 'chest', 'bodyweight', 'beginner', 40,
   'https://www.youtube.com/embed/IODxDxX7oi4', 'https://img.youtube.com/vi/IODxDxX7oi4/hqdefault.jpg',
   'Brace core, lower chest to floor, press up smoothly.'),
  ('dumbbell-chest-press', 'Dumbbell chest press', 'chest', 'dumbbell', 'beginner', 45,
   'https://www.youtube.com/embed/VmB1G1K7v94', 'https://img.youtube.com/vi/VmB1G1K7v94/hqdefault.jpg',
   'Press dumbbells up from mid-chest without shrugging.'),
  ('dumbbell-fly', 'Dumbbell fly', 'chest', 'dumbbell', 'intermediate', 40,
   'https://www.youtube.com/embed/eozdVDA78K0', 'https://img.youtube.com/vi/eozdVDA78K0/hqdefault.jpg',
   'Soft elbows, open wide, squeeze the chest at the top.'),

  -- Back (3)
  ('dumbbell-row', 'Dumbbell row', 'back', 'dumbbell', 'beginner', 45,
   'https://www.youtube.com/embed/roCP6wCXPqo', 'https://img.youtube.com/vi/roCP6wCXPqo/hqdefault.jpg',
   'Pull elbow back, keep torso still.'),
  ('pull-up', 'Pull-up', 'back', 'bodyweight', 'intermediate', 45,
   'https://www.youtube.com/embed/eGo4IYlbE5g', 'https://img.youtube.com/vi/eGo4IYlbE5g/hqdefault.jpg',
   'Pull chest to the bar, control the lower.'),
  ('dumbbell-reverse-fly', 'Dumbbell reverse fly', 'back', 'dumbbell', 'beginner', 40,
   'https://www.youtube.com/embed/PpTFvRTYfpw', 'https://img.youtube.com/vi/PpTFvRTYfpw/hqdefault.jpg',
   'Hinge forward, raise arms wide, squeeze shoulder blades.'),

  -- Shoulders (3)
  ('overhead-press', 'Dumbbell overhead press', 'shoulders', 'dumbbell', 'intermediate', 40,
   'https://www.youtube.com/embed/qEwKCR5JCog', 'https://img.youtube.com/vi/qEwKCR5JCog/hqdefault.jpg',
   'Press up without arching the lower back.'),
  ('lateral-raise', 'Dumbbell lateral raise', 'shoulders', 'dumbbell', 'beginner', 35,
   'https://www.youtube.com/embed/3VcKaXpzqRo', 'https://img.youtube.com/vi/3VcKaXpzqRo/hqdefault.jpg',
   'Lead with elbows, stop near shoulder height.'),
  ('front-raise', 'Dumbbell front raise', 'shoulders', 'dumbbell', 'beginner', 35,
   'https://www.youtube.com/embed/-t7fuZ0KhDA', 'https://img.youtube.com/vi/-t7fuZ0KhDA/hqdefault.jpg',
   'Reach forward as you lift; keep a soft elbow.'),

  -- Arms (3)
  ('dumbbell-bicep-curl', 'Dumbbell bicep curl', 'arms', 'dumbbell', 'beginner', 35,
   'https://www.youtube.com/embed/ykJmrZ5v0Oo', 'https://img.youtube.com/vi/ykJmrZ5v0Oo/hqdefault.jpg',
   'Curl without swinging; keep upper arms still.'),
  ('hammer-curl', 'Hammer curl', 'arms', 'dumbbell', 'beginner', 35,
   'https://www.youtube.com/embed/zC3nLlEvin4', 'https://img.youtube.com/vi/zC3nLlEvin4/hqdefault.jpg',
   'Neutral grip, squeeze at the top, control the lower.'),
  ('tricep-kickback', 'Tricep kickback', 'arms', 'dumbbell', 'beginner', 35,
   'https://www.youtube.com/embed/6SS6K3lAwZ8', 'https://img.youtube.com/vi/6SS6K3lAwZ8/hqdefault.jpg',
   'Hinge forward, pin elbow, extend the forearm fully.'),

  -- Glutes (3)
  ('glute-bridge', 'Glute bridge', 'glutes', 'bodyweight', 'beginner', 40,
   'https://www.youtube.com/embed/OUgsJ8-Vi0E', 'https://img.youtube.com/vi/OUgsJ8-Vi0E/hqdefault.jpg',
   'Drive through heels and squeeze glutes at the top.'),
  ('hip-thrust', 'Hip thrust', 'glutes', 'bodyweight', 'intermediate', 45,
   'https://www.youtube.com/embed/SEdqd1n0cvg', 'https://img.youtube.com/vi/SEdqd1n0cvg/hqdefault.jpg',
   'Upper back on bench, drive hips up, squeeze hard at the top.'),
  ('hip-thrust-form', 'Hip thrust form check', 'glutes', 'bodyweight', 'intermediate', 50,
   'https://www.youtube.com/embed/xDmFkJxPzeM', 'https://img.youtube.com/vi/xDmFkJxPzeM/hqdefault.jpg',
   'Keep ribs down, chin tucked, full hip extension without over-arching.'),

  -- Core (3)
  ('plank', 'Forearm plank', 'core', 'bodyweight', 'beginner', 45,
   'https://www.youtube.com/embed/ASdvN_XEl_c', 'https://img.youtube.com/vi/ASdvN_XEl_c/hqdefault.jpg',
   'Keep hips level and ribs down.'),
  ('bicycle-crunch', 'Bicycle crunch', 'core', 'bodyweight', 'beginner', 40,
   'https://www.youtube.com/embed/9FGilxCbdz8', 'https://img.youtube.com/vi/9FGilxCbdz8/hqdefault.jpg',
   'Rotate elbow to opposite knee with control.'),
  ('dead-bug', 'Dead bug', 'core', 'bodyweight', 'beginner', 40,
   'https://www.youtube.com/embed/4XLEnwUr1d8', 'https://img.youtube.com/vi/4XLEnwUr1d8/hqdefault.jpg',
   'Press low back down, move opposite arm and leg slowly.'),

  -- Hamstrings (3)
  ('romanian-deadlift', 'Romanian deadlift', 'hamstrings', 'dumbbell', 'intermediate', 50,
   'https://www.youtube.com/embed/jEy_czb3RKA', 'https://img.youtube.com/vi/jEy_czb3RKA/hqdefault.jpg',
   'Hinge at hips, slight knee bend, flat back.'),
  ('dumbbell-rdl', 'Dumbbell Romanian deadlift', 'hamstrings', 'dumbbell', 'beginner', 45,
   'https://www.youtube.com/embed/FQKfr1YDhEk', 'https://img.youtube.com/vi/FQKfr1YDhEk/hqdefault.jpg',
   'Feel the hamstring stretch; keep chest up and shoulder blades back.'),
  ('single-leg-rdl', 'Single-leg stiff-leg deadlift', 'hamstrings', 'dumbbell', 'intermediate', 50,
   'https://www.youtube.com/embed/DGavj41F_Cs', 'https://img.youtube.com/vi/DGavj41F_Cs/hqdefault.jpg',
   'Hinge on one leg, keep hips square, soft standing knee.'),

  -- Cardio (3)
  ('jumping-jack', 'Jumping jack', 'cardio', 'bodyweight', 'beginner', 40,
   'https://www.youtube.com/embed/iSSAk4XCsRA', 'https://img.youtube.com/vi/iSSAk4XCsRA/hqdefault.jpg',
   'Land softly and keep a steady rhythm.'),
  ('mountain-climber', 'Mountain climber', 'cardio', 'bodyweight', 'intermediate', 40,
   'https://www.youtube.com/embed/nmwgirgXLYM', 'https://img.youtube.com/vi/nmwgirgXLYM/hqdefault.jpg',
   'Drive knees in under a strong plank.'),
  ('burpee', 'Burpee', 'cardio', 'bodyweight', 'intermediate', 45,
   'https://www.youtube.com/embed/wS4OsJ4yzx4', 'https://img.youtube.com/vi/wS4OsJ4yzx4/hqdefault.jpg',
   'Squat, plank, optional push-up, then jump up tall.'),

  -- Mobility (3)
  ('hip-flexor-stretch', 'Hip flexor stretch', 'mobility', 'bodyweight', 'beginner', 60,
   'https://www.youtube.com/embed/YQmpO9VT2X4', 'https://img.youtube.com/vi/YQmpO9VT2X4/hqdefault.jpg',
   'Tuck pelvis gently and breathe into the front hip.'),
  ('cat-cow', 'Cat-cow stretch', 'mobility', 'bodyweight', 'beginner', 45,
   'https://www.youtube.com/embed/kqnua4rHVVA', 'https://img.youtube.com/vi/kqnua4rHVVA/hqdefault.jpg',
   'Move slowly with the breath; round and open the spine.'),
  ('childs-pose', 'Child''s pose', 'mobility', 'bodyweight', 'beginner', 60,
   'https://www.youtube.com/embed/_ZX_zTOBgp8', 'https://img.youtube.com/vi/_ZX_zTOBgp8/hqdefault.jpg',
   'Sit hips toward heels, reach arms forward, relax the shoulders.'),

  -- Machines (replace unavailable / wrong clips)
  ('leg-press', 'Leg press machine', 'legs', 'machine', 'beginner', 45,
   'https://www.youtube.com/embed/obqVU1u3Bfk', 'https://img.youtube.com/vi/obqVU1u3Bfk/hqdefault.jpg',
   'Feet mid-platform, press through heels, stop short of locking knees.'),
  ('lat-pulldown', 'Lat pulldown machine', 'back', 'machine', 'beginner', 45,
   'https://www.youtube.com/embed/CAwf7n6Luuc', 'https://img.youtube.com/vi/CAwf7n6Luuc/hqdefault.jpg',
   'Pull bar to upper chest, elbows down, control the return.'),
  ('seated-cable-row', 'Seated cable row', 'back', 'cable', 'beginner', 45,
   'https://www.youtube.com/embed/GZbfZ033f74', 'https://img.youtube.com/vi/GZbfZ033f74/hqdefault.jpg',
   'Tall chest, pull handles to ribs, squeeze shoulder blades.'),
  ('chest-press-machine', 'Chest press machine', 'chest', 'machine', 'beginner', 40,
   'https://www.youtube.com/embed/VmB1G1K7v94', 'https://img.youtube.com/vi/VmB1G1K7v94/hqdefault.jpg',
   'Handles at mid-chest, press out smoothly without shrugging.'),
  ('shoulder-press-machine', 'Shoulder press machine', 'shoulders', 'machine', 'beginner', 40,
   'https://www.youtube.com/embed/mASexvk7tEE', 'https://img.youtube.com/vi/mASexvk7tEE/hqdefault.jpg',
   'Press overhead without arching the lower back.'),
  ('pec-deck', 'Pec deck / fly machine', 'chest', 'machine', 'beginner', 40,
   'https://www.youtube.com/embed/eozdVDA78K0', 'https://img.youtube.com/vi/eozdVDA78K0/hqdefault.jpg',
   'Soft elbows, bring pads together in front of the chest.'),
  ('leg-curl-machine', 'Lying leg curl machine', 'hamstrings', 'machine', 'beginner', 40,
   'https://www.youtube.com/embed/1Tq3QdYUuHs', 'https://img.youtube.com/vi/1Tq3QdYUuHs/hqdefault.jpg',
   'Curl heels toward glutes, keep hips glued to the pad.'),
  ('leg-extension', 'Leg extension machine', 'legs', 'machine', 'beginner', 40,
   'https://www.youtube.com/embed/YyvSfVjQeL0', 'https://img.youtube.com/vi/YyvSfVjQeL0/hqdefault.jpg',
   'Extend knees fully with control; avoid kicking the weight.'),
  ('cable-tricep-pushdown', 'Cable tricep pushdown', 'arms', 'cable', 'beginner', 35,
   'https://www.youtube.com/embed/2-LAMcpzODU', 'https://img.youtube.com/vi/2-LAMcpzODU/hqdefault.jpg',
   'Elbows pinned to sides, push down until arms straighten.'),
  ('cable-bicep-curl', 'Cable bicep curl', 'arms', 'cable', 'beginner', 35,
   'https://www.youtube.com/embed/ykJmrZ5v0Oo', 'https://img.youtube.com/vi/ykJmrZ5v0Oo/hqdefault.jpg',
   'Curl without swinging; keep upper arms still.'),
  ('smith-squat', 'Smith machine squat', 'legs', 'machine', 'intermediate', 50,
   'https://www.youtube.com/embed/AHnX-aimA4E', 'https://img.youtube.com/vi/AHnX-aimA4E/hqdefault.jpg',
   'Bar on upper traps, feet slightly forward, keep knees tracking toes.'),
  ('assisted-pullup', 'Assisted pull-up machine', 'back', 'machine', 'beginner', 45,
   'https://www.youtube.com/embed/eGo4IYlbE5g', 'https://img.youtube.com/vi/eGo4IYlbE5g/hqdefault.jpg',
   'Use enough assist to finish clean reps with full range.'),
  ('treadmill-intervals', 'Treadmill intervals', 'cardio', 'cardio_machine', 'beginner', 60,
   'https://www.youtube.com/embed/8i3Vrd95o2k', 'https://img.youtube.com/vi/8i3Vrd95o2k/hqdefault.jpg',
   'Alternate brisk walk and easy jog; hold rails lightly only if needed.'),
  ('elliptical', 'Elliptical trainer', 'cardio', 'cardio_machine', 'beginner', 60,
   'https://www.youtube.com/embed/M4j_vJlfZvs', 'https://img.youtube.com/vi/M4j_vJlfZvs/hqdefault.jpg',
   'Tall posture, drive through heels, keep a steady cadence.'),
  ('stationary-bike', 'Stationary bike', 'cardio', 'cardio_machine', 'beginner', 60,
   'https://www.youtube.com/embed/NwwDBARCGgo', 'https://img.youtube.com/vi/NwwDBARCGgo/hqdefault.jpg',
   'Seat so knee is soft at bottom; start easy then build resistance.'),
  ('hip-abductor', 'Hip abductor machine', 'glutes', 'machine', 'beginner', 40,
   'https://www.youtube.com/embed/OjI5OpV6IWA', 'https://img.youtube.com/vi/OjI5OpV6IWA/hqdefault.jpg',
   'Press knees outward against the pads, control the close.'),
  ('cable-face-pull', 'Cable face pull', 'shoulders', 'cable', 'intermediate', 40,
   'https://www.youtube.com/embed/ljgqer1ZpXg', 'https://img.youtube.com/vi/ljgqer1ZpXg/hqdefault.jpg',
   'Pull rope to face, elbows high, externally rotate at the end.'),
  ('hack-squat', 'Hack squat machine', 'legs', 'machine', 'intermediate', 50,
   'https://www.youtube.com/embed/0tn5K9NlCfo', 'https://img.youtube.com/vi/0tn5K9NlCfo/hqdefault.jpg',
   'Feet shoulder-width, descend until thighs parallel, drive up.')
on conflict (slug) do update set
  name = excluded.name,
  muscle_group = excluded.muscle_group,
  equipment = excluded.equipment,
  difficulty = excluded.difficulty,
  duration_seconds = excluded.duration_seconds,
  demo_video_url = excluded.demo_video_url,
  demo_thumbnail_url = excluded.demo_thumbnail_url,
  cues = excluded.cues;
