-- Add more gym demo videos across muscle groups.

insert into public.gym_exercises (
  slug, name, muscle_group, equipment, difficulty, duration_seconds,
  demo_video_url, demo_thumbnail_url, cues
) values
  -- Chest
  ('decline-dumbbell-press', 'Decline dumbbell press', 'chest', 'dumbbell', 'intermediate', 45,
   'https://www.youtube.com/embed/8iPEnn-ltC8', 'https://img.youtube.com/vi/8iPEnn-ltC8/hqdefault.jpg',
   'Slight decline, wrists stacked, lower to outer chest with control.'),
  ('cable-crossover', 'Cable crossover', 'chest', 'cable', 'intermediate', 40,
   'https://www.youtube.com/embed/8iPEnn-ltC8', 'https://img.youtube.com/vi/8iPEnn-ltC8/hqdefault.jpg',
   'Soft elbows, sweep hands together at chest height, squeeze.'),
  ('dumbbell-pullover', 'Dumbbell pullover', 'chest', 'dumbbell', 'intermediate', 40,
   'https://www.youtube.com/embed/8iPEnn-ltC8', 'https://img.youtube.com/vi/8iPEnn-ltC8/hqdefault.jpg',
   'Hips stay down, lower the weight behind the head, feel the stretch.'),
  ('landmine-press', 'Landmine press', 'chest', 'dumbbell', 'intermediate', 40,
   'https://www.youtube.com/embed/6Z15_WdXmVw', 'https://img.youtube.com/vi/6Z15_WdXmVw/hqdefault.jpg',
   'Brace hard, press the bar up and slightly forward without flaring ribs.'),

  -- Back
  ('t-bar-row', 'T-bar row', 'back', 'dumbbell', 'intermediate', 45,
   'https://www.youtube.com/embed/FWJR5Ve8bnQ', 'https://img.youtube.com/vi/FWJR5Ve8bnQ/hqdefault.jpg',
   'Hinge, pull toward the lower ribs, keep torso still.'),
  ('straight-arm-pulldown', 'Straight-arm pulldown', 'back', 'cable', 'beginner', 35,
   'https://www.youtube.com/embed/brhRXlOhsAM', 'https://img.youtube.com/vi/brhRXlOhsAM/hqdefault.jpg',
   'Arms mostly straight, drive the bar to the thighs, squeeze lats.'),
  ('inverted-row', 'Inverted row', 'back', 'bodyweight', 'beginner', 40,
   'https://www.youtube.com/embed/brhRXlOhsAM', 'https://img.youtube.com/vi/brhRXlOhsAM/hqdefault.jpg',
   'Body in one line, pull chest to the bar, control the lower.'),
  ('single-arm-cable-row', 'Single-arm cable row', 'back', 'cable', 'beginner', 40,
   'https://www.youtube.com/embed/GZbfZ033f74', 'https://img.youtube.com/vi/GZbfZ033f74/hqdefault.jpg',
   'Pull elbow to the hip, avoid rotating the torso.'),
  ('dead-hang', 'Dead hang', 'back', 'bodyweight', 'beginner', 40,
   'https://www.youtube.com/embed/brhRXlOhsAM', 'https://img.youtube.com/vi/brhRXlOhsAM/hqdefault.jpg',
   'Pack the shoulders, hang tall, breathe steadily.'),

  -- Shoulders
  ('military-press', 'Military press', 'shoulders', 'dumbbell', 'intermediate', 45,
   'https://www.youtube.com/embed/2yjwXTZQDDI', 'https://img.youtube.com/vi/2yjwXTZQDDI/hqdefault.jpg',
   'Brace glutes and abs, press straight up, lock out without leaning back.'),
  ('dumbbell-rear-delt-raise', 'Dumbbell rear delt raise', 'shoulders', 'dumbbell', 'beginner', 35,
   'https://www.youtube.com/embed/PpTFvRTYfpw', 'https://img.youtube.com/vi/PpTFvRTYfpw/hqdefault.jpg',
   'Hinge slightly, sweep arms out with soft elbows, squeeze rear delts.'),
  ('cable-rear-delt-fly', 'Cable rear delt fly', 'shoulders', 'cable', 'beginner', 35,
   'https://www.youtube.com/embed/PpTFvRTYfpw', 'https://img.youtube.com/vi/PpTFvRTYfpw/hqdefault.jpg',
   'Cross cables, pull out and back, keep wrists neutral.'),
  ('band-face-pull', 'Band face pull', 'shoulders', 'cable', 'beginner', 35,
   'https://www.youtube.com/embed/ljgqer1ZpXg', 'https://img.youtube.com/vi/ljgqer1ZpXg/hqdefault.jpg',
   'Pull toward the face, elbows high, externally rotate at the end.'),

  -- Arms
  ('ez-bar-curl', 'EZ-bar curl', 'arms', 'dumbbell', 'beginner', 35,
   'https://www.youtube.com/embed/zC3nLlEvin4', 'https://img.youtube.com/vi/zC3nLlEvin4/hqdefault.jpg',
   'Elbows pinned to sides, curl without swinging the hips.'),
  ('incline-curl', 'Incline dumbbell curl', 'arms', 'dumbbell', 'intermediate', 35,
   'https://www.youtube.com/embed/ykJmrZ5v0Oo', 'https://img.youtube.com/vi/ykJmrZ5v0Oo/hqdefault.jpg',
   'Sit back on an incline bench, full stretch at the bottom, curl up.'),
  ('overhead-tricep-extension', 'Overhead tricep extension', 'arms', 'dumbbell', 'beginner', 35,
   'https://www.youtube.com/embed/2-LAMcpzODU', 'https://img.youtube.com/vi/2-LAMcpzODU/hqdefault.jpg',
   'Elbows point up, lower behind the head, extend without flaring.'),
  ('cable-overhead-extension', 'Cable overhead extension', 'arms', 'cable', 'beginner', 35,
   'https://www.youtube.com/embed/2-LAMcpzODU', 'https://img.youtube.com/vi/2-LAMcpzODU/hqdefault.jpg',
   'Rope or bar behind the head, extend fully, control the return.'),

  -- Legs / hamstrings
  ('front-squat', 'Front squat', 'legs', 'dumbbell', 'intermediate', 50,
   'https://www.youtube.com/embed/aclHkVaku9U', 'https://img.youtube.com/vi/aclHkVaku9U/hqdefault.jpg',
   'Elbows high, sit between the hips, keep the torso upright.'),
  ('goblet-reverse-lunge', 'Goblet reverse lunge', 'legs', 'dumbbell', 'beginner', 40,
   'https://www.youtube.com/embed/L8fvypPrzzs', 'https://img.youtube.com/vi/L8fvypPrzzs/hqdefault.jpg',
   'Hold weight at the chest, step back, front knee tracks mid-foot.'),
  ('sissy-squat', 'Sissy squat', 'legs', 'bodyweight', 'advanced', 40,
   'https://www.youtube.com/embed/aclHkVaku9U', 'https://img.youtube.com/vi/aclHkVaku9U/hqdefault.jpg',
   'Lean back, keep hips forward, control the knee bend.'),
  ('nordic-curl', 'Nordic curl', 'hamstrings', 'bodyweight', 'advanced', 45,
   'https://www.youtube.com/embed/FQKfr1YDhEk', 'https://img.youtube.com/vi/FQKfr1YDhEk/hqdefault.jpg',
   'Hips tall, lower slowly with the hamstrings, catch with hands if needed.'),
  ('seated-leg-curl', 'Seated leg curl machine', 'hamstrings', 'machine', 'beginner', 40,
   'https://www.youtube.com/embed/aclHkVaku9U', 'https://img.youtube.com/vi/aclHkVaku9U/hqdefault.jpg',
   'Pad on lower calves, curl heels under the seat, squeeze hamstrings.'),
  ('trap-bar-deadlift', 'Trap-bar deadlift', 'legs', 'dumbbell', 'intermediate', 55,
   'https://www.youtube.com/embed/op9kVnSso6Q', 'https://img.youtube.com/vi/op9kVnSso6Q/hqdefault.jpg',
   'Stand inside the bar, brace, drive the floor away, lock out tall.'),

  -- Glutes
  ('frog-pump', 'Frog pump', 'glutes', 'bodyweight', 'beginner', 35,
   'https://www.youtube.com/embed/SJ1Xuz9D-ZQ', 'https://img.youtube.com/vi/SJ1Xuz9D-ZQ/hqdefault.jpg',
   'Soles of feet together, drive hips up, squeeze glutes hard.'),
  ('banded-side-step', 'Banded side step', 'glutes', 'bodyweight', 'beginner', 35,
   'https://www.youtube.com/embed/OUgsJ8-Vi0E', 'https://img.youtube.com/vi/OUgsJ8-Vi0E/hqdefault.jpg',
   'Soft knees, stay low, step sideways without letting the band snap shut.'),
  ('single-leg-glute-bridge', 'Single-leg glute bridge', 'glutes', 'bodyweight', 'intermediate', 40,
   'https://www.youtube.com/embed/SJ1Xuz9D-ZQ', 'https://img.youtube.com/vi/SJ1Xuz9D-ZQ/hqdefault.jpg',
   'One foot planted, drive through the heel, keep hips level.'),

  -- Core
  ('ab-wheel-rollout', 'Ab wheel rollout', 'core', 'bodyweight', 'advanced', 40,
   'https://www.youtube.com/embed/9FGilxCbdz8', 'https://img.youtube.com/vi/9FGilxCbdz8/hqdefault.jpg',
   'Brace hard, roll out without sagging the low back, pull back in.'),
  ('v-up', 'V-up', 'core', 'bodyweight', 'intermediate', 35,
   'https://www.youtube.com/embed/9FGilxCbdz8', 'https://img.youtube.com/vi/9FGilxCbdz8/hqdefault.jpg',
   'Reach hands and feet up together, lower with control.'),
  ('toe-touch-crunch', 'Toe-touch crunch', 'core', 'bodyweight', 'beginner', 30,
   'https://www.youtube.com/embed/9FGilxCbdz8', 'https://img.youtube.com/vi/9FGilxCbdz8/hqdefault.jpg',
   'Legs up, crunch ribs toward toes, keep low back pressed down.'),
  ('hanging-leg-raise', 'Hanging leg raise', 'core', 'bodyweight', 'intermediate', 40,
   'https://www.youtube.com/embed/RD_A-Z15ER4', 'https://img.youtube.com/vi/RD_A-Z15ER4/hqdefault.jpg',
   'Dead hang, raise legs without swinging, control the descent.'),

  -- Full body / cardio
  ('battle-ropes', 'Battle ropes', 'cardio', 'bodyweight', 'intermediate', 40,
   'https://www.youtube.com/embed/wS4OsJ4yzx4', 'https://img.youtube.com/vi/wS4OsJ4yzx4/hqdefault.jpg',
   'Athletic stance, whip the ropes with soft knees and packed shoulders.'),
  ('assault-bike', 'Assault bike', 'cardio', 'cardio_machine', 'intermediate', 60,
   'https://www.youtube.com/embed/M4j_vJlfZvs', 'https://img.youtube.com/vi/M4j_vJlfZvs/hqdefault.jpg',
   'Drive arms and legs together, stay tall through the torso.'),
  ('shadow-boxing', 'Shadow boxing', 'cardio', 'bodyweight', 'beginner', 45,
   'https://www.youtube.com/embed/iSSAk4XCsRA', 'https://img.youtube.com/vi/iSSAk4XCsRA/hqdefault.jpg',
   'Light footwork, jab-cross rhythm, keep hands up and core braced.'),
  ('medicine-ball-slam', 'Medicine ball slam', 'full_body', 'dumbbell', 'intermediate', 35,
   'https://www.youtube.com/embed/wS4OsJ4yzx4', 'https://img.youtube.com/vi/wS4OsJ4yzx4/hqdefault.jpg',
   'Reach tall, slam hard through the hips, catch and repeat.'),
  ('walking-farmer-carry', 'Walking farmer carry', 'full_body', 'dumbbell', 'beginner', 45,
   'https://www.youtube.com/embed/Fkzk_RqlYig', 'https://img.youtube.com/vi/Fkzk_RqlYig/hqdefault.jpg',
   'Tall posture, packed shoulders, short quick steps.'),

  -- Forearms / traps
  ('plate-pinch', 'Plate pinch hold', 'forearms', 'dumbbell', 'beginner', 30,
   'https://www.youtube.com/embed/Fkzk_RqlYig', 'https://img.youtube.com/vi/Fkzk_RqlYig/hqdefault.jpg',
   'Pinch plates between thumb and fingers, stand tall without shrugging.'),
  ('cable-shrug', 'Cable shrug', 'traps', 'cable', 'beginner', 30,
   'https://www.youtube.com/embed/cJRVVxmytaM', 'https://img.youtube.com/vi/cJRVVxmytaM/hqdefault.jpg',
   'Elevate shoulders straight up, pause, lower slowly.'),

  -- Mobility
  ('pigeon-pose', 'Pigeon pose', 'mobility', 'bodyweight', 'beginner', 50,
   'https://www.youtube.com/embed/kqnua4rHVVA', 'https://img.youtube.com/vi/kqnua4rHVVA/hqdefault.jpg',
   'Square the hips, breathe into the front hip, keep the back leg long.'),
  ('ninety-ninety-stretch', '90/90 hip stretch', 'mobility', 'bodyweight', 'beginner', 45,
   'https://www.youtube.com/embed/kqnua4rHVVA', 'https://img.youtube.com/vi/kqnua4rHVVA/hqdefault.jpg',
   'Both knees at 90°, sit tall, rotate gently toward each shin.'),
  ('foam-roll-quads', 'Foam roll quads', 'mobility', 'bodyweight', 'beginner', 45,
   'https://www.youtube.com/embed/kqnua4rHVVA', 'https://img.youtube.com/vi/kqnua4rHVVA/hqdefault.jpg',
   'Slow rolls over the front thigh, pause on tight spots, breathe.')
on conflict (slug) do update set
  name = excluded.name,
  muscle_group = excluded.muscle_group,
  equipment = excluded.equipment,
  difficulty = excluded.difficulty,
  duration_seconds = excluded.duration_seconds,
  demo_video_url = excluded.demo_video_url,
  demo_thumbnail_url = excluded.demo_thumbnail_url,
  cues = excluded.cues;
